[package]
name = "tine"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
rmp-serde = "1.3.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["fs", "full", "net", "tracing"] }
